application: 19blocks
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

#- url: /favicon\.ico
#  static_files: favicon.ico
#  upload: favicon\.ico
#- url: /static/app/(.*\.js)
#  mime_type: text/javascript
#  static_files: static/\1
#  upload: static/(.*\.js)
#- url: /static/app.js
#  static_dir: static

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /static/app.js
  static_files: static/app.js
  upload: static/app.js
- url: /app
  static_dir: static/app
- url: .*
  script: main.app

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (/static/metadata/.*)|
 )$

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest